name: Tests

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['7.2']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Build Image
        run: |
          docker build . -t testbucket-image

      - name: Start Container
        run: |
          docker run -d --rm --name testbucket-container testbucket-image

      - name: Run tests
        run: |
          docker exec testbucket-container vendor/bin/phpunit
